/**
 * @typedef {Object} AIContext
 * @property {string} userId - The ID of the user interacting with the AI.
 * @property {string} companyId - The ID of the company to scope data appropriately.
 * @property {string} role - The user's role in the company.
 * @property {string} conversationId - The current conversation ID.
 */

/**
 * @typedef {Object} Source
 * @property {string} id - Unique identifier for the source.
 * @property {string} [title] - Title of the source document/chunk.
 * @property {string} [type] - Type of source (e.g., 'labor_law', 'company_policy').
 * @property {string} [url] - URL to the source, if available.
 * @property {string} [chunkId] - Specific chunk ID in vector storage.
 * @property {number} [relevanceScore] - Retrieval relevance score.
 */

/**
 * @typedef {Object} Action
 * @property {string} type - The type of action (e.g., 'submit_leave_request').
 * @property {unknown} [payload] - Action-specific payload data.
 */

/**
 * @typedef {Object} SkillResult
 * @property {boolean} success - Whether the skill execution succeeded.
 * @property {unknown} [data] - Skill execution data/result.
 * @property {string} [message] - Message returned from the skill.
 * @property {Source[]} [sources] - Sources used by the skill.
 * @property {Action} [action] - An action recommended or triggered by the skill.
 */

/**
 * @typedef {Object} AISkill
 * @property {string} name - Name of the skill.
 * @property {string} description - Description of the skill.
 * @property {unknown} inputSchema - Schema defining expected input (e.g., Zod schema).
 * @property {function(unknown, AIContext): Promise<SkillResult>} execute - Executes the skill logic.
 */

/**
 * @typedef {Object} AITool
 * @property {string} name - Name of the tool.
 * @property {string} description - Description of the tool.
 * @property {unknown} inputSchema - Schema defining expected input (e.g., Zod schema).
 * @property {function(unknown, AIContext): Promise<SkillResult>} execute - Executes the tool logic.
 */

/**
 * @typedef {Object} ChatResponse
 * @property {string} conversationId - The conversation ID.
 * @property {string} message - The response message generated by the AI.
 * @property {"text" | "action"} type - The type of response.
 * @property {Source[]} sources - Citations/sources used in the response.
 * @property {Action[]} actions - Actions returned by the AI.
 */

/**
 * @typedef {Object} OrchestratorInput
 * @property {string} message - The user's input message.
 * @property {AIContext} context - The AI context.
 * @property {Object[]} [history] - Optional conversation history.
 */

export {};
